interfaces = []
exclude = [
    ".*__pycache__",
    ".*egg-info",
    "docs",
    "tests",
]
source_roots = [
    ".",
]

[[modules]]
path = "<root>"
depends_on = [
    { path = "posthog" },
]

[[modules]]
path = "ee"
depends_on = [
    { path = "hogvm.python" },
    { path = "posthog" },
]

[[modules]]
path = "hogql_parser"
depends_on = []

[[modules]]
path = "hogvm.python"
depends_on = [
    { path = "posthog" },
]

[[modules]]
path = "posthog"
depends_on = [
    { path = "<root>" },
    { path = "ee" },
    { path = "hogql_parser" },
    { path = "hogvm.python" },
    { path = "products.early_access_features" },
]

[[modules]]
path = "products.early_access_features"
depends_on = [
    { path = "posthog" },
]

[[modules]]
path = "products.messaging"
depends_on = []
